apiVersion: v1
kind: Secret
metadata:
  name: assemblyline-system-passwords
type: Opaque
stringData:
  datastore-password: devpass
    # Logging password has to be set to the same as database password if you want to use the same DB for data and logging
  logging-password: devpass
    # If this is the password for backends like azure blob storage, the password may need to be url encoded
    # if it includes non alphanum characters
  filestore-password: filestore
  initial-admin-password: admin