# Tags for the containers used
release: "dev"

# Images for containers used
assemblylineCoreImage: localhost:32000/cccs/assemblyline
assemblylineUIImage: localhost:32000/cccs/assemblyline
assemblylineSocketIOImage: localhost:32000/cccs/assemblyline
assemblylineServiceAPIImage: localhost:32000/cccs/assemblyline
assemblylineFrontendImage: localhost:32000/cccs/assemblyline-ui-frontend
assemblylineServiceImagePrefix: localhost:32000/cccs/assemblyline-service-

autoInstallServices: []

ingressAnnotations:
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/proxy-body-size: 100m

enableCoreDebugging: true
# Set the default storage classes for microk8s
redisStorageClass: microk8s-hostpath
persistantStorageClass: microk8s-hostpath

# Turn off replication since there is only one elastic node
#   NOTE: If you decide to add more datastore node this should be set
#         to 1 once there are more then 3 datastore nodes
elasticDefaultReplicas: 0

# Turn off logs gathering to saved on processing power, you can still have access
# to logs via kubectl or Lens
#   NOTE: This could be turned back on if the appliance node is powerful enough
#         If you turn it on, make sure you set internalELKStack to true as well
enableLogging: false

# Turn off metrics gathering to saved on processing power (This uses a lot of CPU/Memory)
#   NOTE: This could be turned back on if the appliance node is powerful enough
#         If you turn it on, make sure you set internalELKStack to true as well
enableMetrics: false

# Turn off Application performance metrics to save processing power
#   NOTE: This could be turned back on if you need insight on the performance of the core components
#         If you turn it on, make sure you set internalELKStack to true as well
#         ** You will only need this if you are doing development on core components
enableAPM: false

# Turn off self contained ELK stack for logging and metrics
#   NOTE: Do no forget to turn this on if you enable either logging, metrics or APM
internalELKStack: false

# Make sure we use the same elasticsearch DB for logging and data when
# internal logging is turned on.
#   NOTE: This should never be set to true for an appliance
seperateInternalELKStack: false

# Set kibana to use the internal ELK Stack if logging is turned on
kibana:
  elasticsearchHosts: http://datastore-master:9200

# Stop reserving CPU for component
#    NOTE: This prevent HPAs to scale core components, only use on very small
#          systems. If your appliance is bigger, you should consider commenting
#          those values because they will increase the throughput of your system
#          under heavy load. (Default reservation values for all core component is
#          around 8 cores.)
defaultReqCPU: "0m"
alerterReqCPU: "0m"
apmReqCPU: "0m"
dispatcherReqCPU: "0m"
elasticHelperReqCPU: "0m"
esMetricsReqCPU: "0m"
expiryReqCPU: "0m"
frontendReqCPU: "0m"
heartbeatReqCPU: "0m"
internalUIReqCPU: "0m"
ingestUIReqCPU: "0m"
ingesterReqCPU: "0m"
logstashReqCPU: "0m"
metricsReqCPU: "0m"
plumberReqCPU: "0m"
redisVolatileReqCPU: "0m"
redisPersistentReqCPU: "0m"
scalerReqCPU: "0m"
serviceServerReqCPU: "0m"
socketIOReqCPU: "0m"
statisticsReqCPU: "0m"
uiReqCPU: "0m"
updaterReqCPU: "0m"
workflowReqCPU: "0m"

coreVolumes:
  - name: assemblyline-packages
    hostPath:
      path: placeholder_for_packages
      type: Directory
coreMounts:
  - name: assemblyline-packages
    mountPath: /opt/alv4

# Internal configuration for assemblyline components. See the assemblyline
# administration documentation for more details.
# https://cybercentrecanada.github.io/assemblyline4_docs/
configuration:
  core:
    scaler:
      service_defaults:
        min_instances: 0
  logging:
    log_level: INFO
  services:
    # CPU reservation as been lowered so we could squeeze more services into smaller appliance
    #   If you are having issues with services timing out a lot under heavy load, bring it back
    #   to its default 0.6 value.
    cpu_reservation: 0.4
    image_variables:
      REGISTRY: "localhost:32000/"
    allow_insecure_registry: true
  submission:
    max_file_size: 157286400
  ui:
    fqdn: "localhost"

# Configuration for the elasticsearch instance used for system data.
#   NOTE: Make sure you adjust the maximum storage size to a value appropriate
#         to your system as the default value is quite small.
datastore:
  replicas: 1
  esJavaOpts: "-Xms2g -Xmx2g"
  resources:
    requests:
      memory: 2Gi
  volumeClaimTemplate:
    storageClassName: microk8s-hostpath
    resources:
      requests:
        storage: 20Gi

# Configuration for the file storage
#   NOTE: Make sure you adjust the max amount of storage files can take
#         on your system to a proper value as the default is quite small
filestore:
  persistence:
    size: 20Gi
    StorageClass: microk8s-hostpath
  resources:
    requests:
      memory: 2Gi
